name: Preview Deploy + E2E

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  unit-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Unit tests
        run: pnpm test -- --coverage

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

  preview-and-e2e:
    needs: unit-and-lint
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Pull Vercel env (preview)
        run: pnpm dlx vercel@latest pull --yes --environment=preview --token "$VERCEL_TOKEN"

      - name: Build locally using Vercel
        run: pnpm dlx vercel@latest build --token "$VERCEL_TOKEN"

      - name: Deploy prebuilt to Vercel (preview)
        id: deploy
        run: |
          URL=$(pnpm -s dlx vercel@latest deploy --prebuilt --token "$VERCEL_TOKEN")
          echo "preview_url=$URL" >> $GITHUB_OUTPUT

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run E2E against preview URL
        env:
          PLAYWRIGHT_BASE_URL: ${{ steps.deploy.outputs.preview_url }}
          VERCEL_ENV: preview
        run: pnpm test:e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
